# .render.yaml
services:
  - type: web
    name: server
    env: node
    nodeVersion: 20.15.1
    buildCommand: pnpm install
    startCommand: pnpm start
    rootDirectory: portfolio/server
    plan: free
    port: 3000
